disabled_rules:
  - line_length
  - trailing_whitespace
  - identifier_name

included:
  - gympeople

excluded:
  - Pods
  - Config

opt_in_rules:
  - empty_count
  - force_unwrapping

reporter: "xcode"
